{% set name = "apricot-select" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apricot-select-{{ version }}.tar.gz
    sha256: 3bf872d43ee96af141c9e4c40e4359aa6ca5e3022ae43b2a8aa46b24947b8bd8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.14.2
    - scipy >=1.0.0
    - numba >=0.43.0
    - tqdm >=4.24.0
    - nose
    # dependency missing in setup.py (#39), needs to be >= 0.22 for sklearn.neighbors.KNeighborsTransformer 
    - scikit-learn >=0.22

test:
  imports:
    - apricot
    - apricot.optimizers
    - apricot.utils
    - apricot.functions
    - apricot.functions.base
    - apricot.functions.custom
    - apricot.functions.facilityLocation
    - apricot.functions.featureBased
    - apricot.functions.graphCut
    - apricot.functions.maxCoverage
    - apricot.functions.mixture
    - apricot.functions.saturatedCoverage
    - apricot.functions.sumRedundancy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/apricot-select/
  summary: apricot is a package for submodular selection of representative sets for machine learning models.
  license: MIT
  # jmschrei did not pack the LICENCE file in the pypi release (#34), file is included in the recipe
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
